from enum import Enum


class Verdict(Enum):
    FAILED = 1
    OK = 2
    PARTIAL = 3
    COMPILATION_ERROR = 4
    RUNTIME_ERROR = 5
    WRONG_ANSWER = 6
    PRESENTATION_ERROR = 7
    TIME_LIMIT_EXCEEDED = 8
    MEMORY_LIMIT_EXCEEDED = 9
    IDLENESS_LIMIT_EXCEEDED = 10
    SECURITY_VIOLATED = 11
    CRASHED = 12
    INPUT_PREPARATION_CRASHED = 13
    CHALLENGED = 14
    SKIPPED = 15
    TESTING = 16
    REJECTED = 17
