from enum import Enum


class CfContestType(Enum):
    CF = 'CF'
    IOI = 'IOI'
    ICPC = 'ICPC'


class CfPhase(Enum):
    BEFORE = 'BEFORE'
    CODING = 'CODING'
    PENDING_SYSTEM_TEST = 'PENDING_SYSTEM_TEST'
    SYSTEM_TEST = 'SYSTEM_TEST'
    FINISHED = 'FINISHED'


class CfProblemType(Enum):
    PROGRAMMING = 'PROGRAMMING'
    QUESTION = 'QUESTION'


class CfParticipantType(Enum):
    CONTESTANT = 'CONTESTANT'
    PRACTICE = 'PRACTICE'
    VIRTUAL = 'VIRTUAL'
    MANAGER = 'MANAGER'
    OUT_OF_COMPETITION = 'OUT_OF_COMPETITION'


class CfVerdict(Enum):
    FAILED = 'FAILED'
    OK = 'OK'
    PARTIAL = 'PARTIAL'
    COMPILATION_ERROR = 'COMPILATION_ERROR'
    RUNTIME_ERROR = 'RUNTIME_ERROR'
    WRONG_ANSWER = 'WRONG_ANSWER'
    PRESENTATION_ERROR = 'PRESENTATION_ERROR'
    TIME_LIMIT_EXCEEDED = 'TIME_LIMIT_EXCEEDED'
    MEMORY_LIMIT_EXCEEDED = 'MEMORY_LIMIT_EXCEEDED'
    IDLENESS_LIMIT_EXCEEDED = 'IDLENESS_LIMIT_EXCEEDED'
    SECURITY_VIOLATED = 'SECURITY_VIOLATED'
    CRASHED = 'CRASHED'
    INPUT_PREPARATION_CRASHED = 'INPUT_PREPARATION_CRASHED'
    CHALLENGED = 'CHALLENGED'
    SKIPPED = 'SKIPPED'
    TESTING = 'TESTING'
    REJECTED = 'REJECTED'


class CfTestset(Enum):
    SAMPLES = 'SAMPLES'
    PRETESTS = 'PRETESTS'
    TESTS = 'TESTS'
    CHALLENGES = 'CHALLENGES'
    TESTS1 = 'TESTS1'
    TESTS2 = 'TESTS2'
    TESTS3 = 'TESTS3'
    TESTS4 = 'TESTS4'
    TESTS5 = 'TESTS5'
    TESTS6 = 'TESTS6'
    TESTS7 = 'TESTS7'
    TESTS8 = 'TESTS8'
    TESTS9 = 'TESTS9'
    TESTS10 = 'TESTS10'
