from enum import Enum


class CfContestType(Enum):
    CF = 0
    IOI = 1
    ICPC = 2


class CfPhase(Enum):
    BEFORE = 'BEFORE'
    CODING = 'CODING'
    PENDING_SYSTEM_TEST = 'PENDING_SYSTEM_TEST'
    SYSTEM_TEST = 'SYSTEM_TEST'
    FINISHED = 'FINISHED'


class CfProblemType(Enum):
    PROGRAMMING = 0
    QUESTION = 1


class CfParticipantType(Enum):
    CONTESTANT = 0
    PRACTICE = 1
    VIRTUAL = 2
    MANAGER = 3
    OUT_OF_COMPETITION = 4


class CfVerdict(Enum):
    FAILED = 'FAILED'
    OK = 'OK'
    PARTIAL = 'PARTIAL'
    COMPILATION_ERROR = 'COMPILATION_ERROR'
    RUNTIME_ERROR = 'RUNTIME_ERROR'
    WRONG_ANSWER = 'WRONG_ANSWER'
    PRESENTATION_ERROR = 'PRESENTATION_ERROR'
    TIME_LIMIT_EXCEEDED = 'TIME_LIMIT_EXCEEDED'
    MEMORY_LIMIT_EXCEEDED = 'MEMORY_LIMIT_EXCEEDED'
    IDLENESS_LIMIT_EXCEEDED = 'IDLENESS_LIMIT_EXCEEDED'
    SECURITY_VIOLATED = 'SECURITY_VIOLATED'
    CRASHED = 'CRASHED'
    INPUT_PREPARATION_CRASHED = 'INPUT_PREPARATION_CRASHED'
    CHALLENGED = 'CHALLENGED'
    SKIPPED = 'SKIPPED'
    TESTING = 'TESTING'
    REJECTED = 'REJECTED'


class CfTestset(Enum):
    SAMPLES = 0
    PRETESTS = 1
    TESTS = 2
    CHALLENGES = 3
    TESTS1 = 4
    TESTS2 = 5
    TESTS3 = 6
    TESTS4 = 7
    TESTS5 = 8
    TESTS6 = 9
    TESTS7 = 10
    TESTS8 = 11
    TESTS9 = 12
    TESTS10 = 13
